### ISSUE TITLE
Crashed with TF2 2024-04-18 update

### ISSUE THREAD

**Issue by gaejuck** [redsunservers/SCP-Secret-Fortress#134]
https://crash.limetech.org/qw3x6gax5smm

SourceMod Version Information
```
    SourceMod Version: 1.12.0.7116
    SourcePawn Engine: 1.12.0.7116, jit-x86 (build 1.12.0.7116)
    SourcePawn API: v1 = 5, v2 = 16
    Compiled on: Apr 18 2024 04:45:06
    Built from: https://github.com/alliedmodders/sourcemod/commit/6cac489f
    Build ID: 7116:6cac489f
    http://www.sourcemod.net/
```

Metamod:Source Version Information
```
   Metamod:Source version 1.12.0-dev+1192
   Plugin interface version: 16:14
   SourceHook version: 5:5
   Loaded As: Valve Server Plugin
   Compiled on: Feb  7 2024 16:03:42
   Built from: https://github.com/alliedmodders/metamod-source/commit/837fa2c
   Build ID: 1192:837fa2c
   http://www.metamodsource.net/
```

Additionally, it's running in linux server

**Comment by gaejuck** [comment]
I did update gamedata. but it crashed again.

https://crash.limetech.org/ohxakxlkro7z

**Comment by gaejuck** [comment]
Attribute "4328; 1" seems to cause a crash.
When I remove that attribute from SCP-096 and SCP-939, there is no crash.

**Comment by FortyTwoFortyTwo** [comment]
Attribute 4328 seems to be a hidden one, where [this plugin](https://forums.alliedmods.net/showthread.php?t=326853) enables it. We don't use this plugin anymore, so this attribute being here seems to be a leftover that should've been removed long time ago.

@Batfoxkid am I correct on this?

**Comment by Batfoxkid** [comment]
> Attribute 4328 seems to be a hidden one, where [this plugin](https://forums.alliedmods.net/showthread.php?t=326853) enables it. We don't use this plugin anymore, so this attribute being here seems to be a leftover that should've been removed long time ago.
> 
> @Batfoxkid am I correct on this?

It is indeed a leftover of it using Hidden Dev Attributes.
