### ISSUE TITLE
Possible item cloning bug

### ISSUE THREAD

**Issue by Nic5-Cyprus** [redsunservers/SCP-Secret-Fortress#83]
I was a dboy inside an elevator with a scientist and the scientist had micro. Once the elevator landed chaos was outside and immediately gunned down the scientist. Micro was on the ground and both me and a chaos touched it at the same time and both got it. I tried to use it and it was working so we both had 2 instances of the same item

**Comment by Mikusch** [comment]
This was (probably) fixed with #91.
